language: python
dist: bionic
python:
  - "3.8"

services:
  - docker

env:
  global:
    - VERSION: 0.10.0.${TRAVIS_BUILD_NUMBER}
    - API_SERVER: https://api.lightest.xyz/testing/

script:
- bash build.sh

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master