# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CodeTester.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CodeTester.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\014GrpcServices',
  serialized_pb=b'\n\x10\x43odeTester.proto\"*\n\x0e\x43heckerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"@\n\x0f\x43heckerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x63ompiled\x18\x03 \x01(\x08\"7\n\x04Test\x12\x10\n\x08testName\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\"*\n\x08\x43odeFile\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"\x90\x01\n\x0eTestingRequest\x12\x10\n\x08uploadId\x18\x01 \x01(\t\x12\x13\n\x0bmemoryLimit\x18\x02 \x01(\x05\x12\x11\n\ttimeLimit\x18\x03 \x01(\x05\x12\x11\n\tcheckerId\x18\x04 \x01(\t\x12\x14\n\x05tests\x18\x05 \x03(\x0b\x32\x05.Test\x12\x1b\n\x08\x63odeFile\x18\x06 \x01(\x0b\x32\t.CodeFile\"\x93\x01\n\x0fTestingResponse\x12\x10\n\x08uploadId\x18\x01 \x01(\t\x12\x15\n\rtestingFailed\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x1c\n\x14successfulTestsCount\x18\x05 \x01(\x05\x12\x18\n\x10\x66\x61iledTestsCount\x18\x06 \x01(\x05\"\x16\n\x14\x43heckerStatusRequest\";\n\x15\x43heckerStatusResponse\x12\x0c\n\x04\x66ree\x18\x01 \x01(\x08\x12\x14\n\x0cserverStatus\x18\x02 \x01(\t2\xae\x01\n\nCodeTester\x12\x33\n\x0e\x43ompileChecker\x12\x0f.CheckerRequest\x1a\x10.CheckerResponse\x12/\n\nTestUpload\x12\x0f.TestingRequest\x1a\x10.TestingResponse\x12:\n\tGetStatus\x12\x15.CheckerStatusRequest\x1a\x16.CheckerStatusResponseB\x0f\xaa\x02\x0cGrpcServicesb\x06proto3'
)




_CHECKERREQUEST = _descriptor.Descriptor(
  name='CheckerRequest',
  full_name='CheckerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CheckerRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='CheckerRequest.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=62,
)


_CHECKERRESPONSE = _descriptor.Descriptor(
  name='CheckerResponse',
  full_name='CheckerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CheckerResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='CheckerResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compiled', full_name='CheckerResponse.compiled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=128,
)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='testName', full_name='Test.testName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='Test.input', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='Test.output', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=185,
)


_CODEFILE = _descriptor.Descriptor(
  name='CodeFile',
  full_name='CodeFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='CodeFile.fileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='CodeFile.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=229,
)


_TESTINGREQUEST = _descriptor.Descriptor(
  name='TestingRequest',
  full_name='TestingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uploadId', full_name='TestingRequest.uploadId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memoryLimit', full_name='TestingRequest.memoryLimit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeLimit', full_name='TestingRequest.timeLimit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkerId', full_name='TestingRequest.checkerId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tests', full_name='TestingRequest.tests', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeFile', full_name='TestingRequest.codeFile', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=376,
)


_TESTINGRESPONSE = _descriptor.Descriptor(
  name='TestingResponse',
  full_name='TestingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uploadId', full_name='TestingResponse.uploadId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testingFailed', full_name='TestingResponse.testingFailed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='TestingResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='TestingResponse.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='successfulTestsCount', full_name='TestingResponse.successfulTestsCount', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failedTestsCount', full_name='TestingResponse.failedTestsCount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=526,
)


_CHECKERSTATUSREQUEST = _descriptor.Descriptor(
  name='CheckerStatusRequest',
  full_name='CheckerStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=550,
)


_CHECKERSTATUSRESPONSE = _descriptor.Descriptor(
  name='CheckerStatusResponse',
  full_name='CheckerStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='free', full_name='CheckerStatusResponse.free', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverStatus', full_name='CheckerStatusResponse.serverStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=611,
)

_TESTINGREQUEST.fields_by_name['tests'].message_type = _TEST
_TESTINGREQUEST.fields_by_name['codeFile'].message_type = _CODEFILE
DESCRIPTOR.message_types_by_name['CheckerRequest'] = _CHECKERREQUEST
DESCRIPTOR.message_types_by_name['CheckerResponse'] = _CHECKERRESPONSE
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['CodeFile'] = _CODEFILE
DESCRIPTOR.message_types_by_name['TestingRequest'] = _TESTINGREQUEST
DESCRIPTOR.message_types_by_name['TestingResponse'] = _TESTINGRESPONSE
DESCRIPTOR.message_types_by_name['CheckerStatusRequest'] = _CHECKERSTATUSREQUEST
DESCRIPTOR.message_types_by_name['CheckerStatusResponse'] = _CHECKERSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckerRequest = _reflection.GeneratedProtocolMessageType('CheckerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKERREQUEST,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:CheckerRequest)
  })
_sym_db.RegisterMessage(CheckerRequest)

CheckerResponse = _reflection.GeneratedProtocolMessageType('CheckerResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKERRESPONSE,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:CheckerResponse)
  })
_sym_db.RegisterMessage(CheckerResponse)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:Test)
  })
_sym_db.RegisterMessage(Test)

CodeFile = _reflection.GeneratedProtocolMessageType('CodeFile', (_message.Message,), {
  'DESCRIPTOR' : _CODEFILE,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:CodeFile)
  })
_sym_db.RegisterMessage(CodeFile)

TestingRequest = _reflection.GeneratedProtocolMessageType('TestingRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTINGREQUEST,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:TestingRequest)
  })
_sym_db.RegisterMessage(TestingRequest)

TestingResponse = _reflection.GeneratedProtocolMessageType('TestingResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTINGRESPONSE,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:TestingResponse)
  })
_sym_db.RegisterMessage(TestingResponse)

CheckerStatusRequest = _reflection.GeneratedProtocolMessageType('CheckerStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKERSTATUSREQUEST,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:CheckerStatusRequest)
  })
_sym_db.RegisterMessage(CheckerStatusRequest)

CheckerStatusResponse = _reflection.GeneratedProtocolMessageType('CheckerStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKERSTATUSRESPONSE,
  '__module__' : 'CodeTester_pb2'
  # @@protoc_insertion_point(class_scope:CheckerStatusResponse)
  })
_sym_db.RegisterMessage(CheckerStatusResponse)


DESCRIPTOR._options = None

_CODETESTER = _descriptor.ServiceDescriptor(
  name='CodeTester',
  full_name='CodeTester',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=614,
  serialized_end=788,
  methods=[
  _descriptor.MethodDescriptor(
    name='CompileChecker',
    full_name='CodeTester.CompileChecker',
    index=0,
    containing_service=None,
    input_type=_CHECKERREQUEST,
    output_type=_CHECKERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TestUpload',
    full_name='CodeTester.TestUpload',
    index=1,
    containing_service=None,
    input_type=_TESTINGREQUEST,
    output_type=_TESTINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='CodeTester.GetStatus',
    index=2,
    containing_service=None,
    input_type=_CHECKERSTATUSREQUEST,
    output_type=_CHECKERSTATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CODETESTER)

DESCRIPTOR.services_by_name['CodeTester'] = _CODETESTER

# @@protoc_insertion_point(module_scope)
